name: Convert2RMarkdown

on:
  push:
    paths:
      - mkdocs/
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Convert to R Markdown
      run: |
        cd mkdocs/
        for f in *.md; do
          echo "move file to" "../bookdown/$(basename "$f" .md).Rmd"
          cp "$f" "../bookdown/$(basename "$f" .md).Rmd"
        done