name: Convert2Markdown

on:
  push:
    paths:
      - bookdown/
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Convert to Markdown (bookdown -> readthedocs)
      run: |
        cd bookdown
        for f in *.Rmd; do
          echo "move file to" "../mkdocs/$(basename "$f" .Rmd).md"
          cp "$f" "../mkdocs/$(basename "$f" .Rmd).md"
        done